name: Build AFFT Magisk Module

on:
  workflow_dispatch:

jobs:
  build:
    name: Build AFFT Magisk Module
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Required Packages
        run: |
          sudo apt update

      - name: Clone AFFT
        run: git clone https://github.com/mrx7014/AFFT

      - name: Create AFFT Zip
        run: |
          cd AFFT
          zip -r AFFT-V8.0.0.zip . -x ".git*" -x ".github*" -x "AFFT_Banner.jpg" -x "LICENSE" -x "README.md"
    
      - name: Create a tag
        run: |
          git tag ${{ github.run_id }}
          git push origin ${{ github.run_id }}

      - name: Upload AFFT to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            AFFT/AFFT-V8.0.0.zip
          tag_name: ${{ github.run_id }}
          release_name: AFFT
          body: |
            ${{ github.run_id }}
