name: Build AFFT Module

on:
  workflow_dispatch:
  push:
    branches:
      - Module

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    - name: Create AFFT Zip Archive
      run: |
       git clone https://github.com/mrx7014/AFFT
       cd AFFT
       zip -r AFFT-V8.0.0 . -x ".git*" -x ".github*" -x "AFFT_Banner.jpg" -x "README.md"

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AFFT/AFFT-V8.0.0.zip
        name: AFFT Magisk Module
        tag_name: ${{ github.run_id }}
        body: |
          Device: Samsung Galaxy A23 4G
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
