name: Build AFFT Module

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out
      uses: actions/checkout@v4

    - name: Create AFFT Zip Archive
      run: |
       git clone https://github.com/mrx7014/AFFT
       cd AFFT
       zip -r AFFT-V8.0.0 . -x ".git*" -x ".github*" -x "AFFT_Banner.jpg" -x "README.md"

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AFFT/AFFT-V8.0.0.zip
        name: AFFT Magisk Module
        tag_name: ${{ github.run_id }}
        body: |
          Device: Samsung Galaxy A23 4G
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
